version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gaming_profiles_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gaming_profiles
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../data/raw:/data/raw